Add gaze16-3060-b
pop-os/system76-power pull request #287
Opened 2021-11-01 17:34 UTC by crawfxrd

2021-11-01 18:03 UTC, jackpot51 approved these changes

2021-11-01 18:04 UTC, jackpot51 requested changes
Please bump the version and update debian/changelog

2021-11-02 18:09 UTC, jackpot51 approved these changes

2021-11-02 18:12 UTC, leviport approved these changes

2021-11-02 18:12 UTC, merged