Switching graphics modes wil now add an initrranfs hook
pop-os/system76-power pull request #311
Opened 2022-02-28 20:56 UTC by cwsystem76

Switching graphics modes via `system76-power` will now add a hook script to `/etc/initramfs-tools/hooks/` to add the Nvdia kernel modules to the boot image, when appropriate. The hook will also be removed when the package is uninstalled This is part of the fix for a boot issue on certain hybrid graphics laptops which was originally reported for plymouth (pop-os/plymouth-theme#26).

I've been advised that the code duplication in this PR is frowned upon, but it seemed like the quickest way to get a proof-of-concept going. Advice on whether to move the two piece of code that write `/etc/modprobe.d/system76-power.conf` and `/etc/initramfs-tools/hooks/system76-power` into a function or other more Rustlike thing would be very helpful.

2022-02-28 22:10 UTC, 13r0ck requested changes

2022-02-28 22:10 UTC, 13r0ck commented on src/graphics.rs
> +const INITRAMFS_HOOK_PATH: &str = "/etc/initramfs-tools/hooks/system76-power";
Minor nitpick: keep these in alphabetical order, `INITRAM`... should come after `SYSTEM_SLEEP_S3`, but `PRIME_DISCRETE_PATH` is already out of order so, this isn't a big deal.

2022-02-28 22:20 UTC, cwsystem76 commented on src/graphics.rs
> +        {
I was keeping them separate since they're working on two different files, but since I changed `file` to be hook_file and `modprobe_file` it shouldn't be an issue anymore. Will do.

2022-02-28 22:23 UTC, cwsystem76 commented on src/graphics.rs
> +const INITRAMFS_HOOK_PATH: &str = "/etc/initramfs-tools/hooks/system76-power";
Sorted them anyway.

2022-02-28 22:27 UTC, cwsystem76 commented on src/graphics.rs
> +            let text = if vendor == "hybrid" {
There are two `hook_file.write_all` calls because there were two `modprobe_file.write_all` calls and I wasn't sure if there was a reason for that. If I'm going to combine the two hook calls, I should do the same for modprobe. I'll work on a solution that will work for both.

2022-03-25 23:26 UTC, cwsystem76 commented
This commit (https://github.com/pop-os/system76-power/commit/f17053130e2bacfa9c998ae709599f76e675fb96) just ran roughshod over my changes. I'm going to cancel this PR and start over since I don't think I can safely merge with `master` now without completely rewriting the changes I made.

2022-03-25 23:26 UTC, closed without merging