improv: Use clap 3 derive macro for argument parsing
pop-os/system76-power pull request #312
Opened 2022-03-01 22:22 UTC by ids1024

Using the derive macro seems generally better to add some static verification the argument parsing code.

This seems to be working like the previous version, though `system76-power graphics --help` seems to have sub-commands and their descriptions on seperate lines, when the weren't before. I guess something in `clap` changed related to that...

2022-03-01 23:36 UTC, Absolucy requested changes
Looks good to me, other than the one clippy lint that's easy to resolve.

Clap 3's derive macro results in nicer code, which is always nicer to have :)

2022-03-01 23:36 UTC, Absolucy commented on src/client.rs
> +            if thresholds.len() != 0 {
```suggestion
            if !thresholds.is_empty() {
```

2022-03-02 16:12 UTC, ids1024 commented on src/client.rs
> +            if thresholds.len() != 0 {
Updated. I should probably run `clippy` more regularly.

2022-03-02 16:51 UTC, Absolucy requested changes
Unsure why GitHub says the Jenkins build is failing, considering that the builds seem to have succeeded on Jenkins.

Should be ready after a `cargo fmt`.

2022-03-10 21:55 UTC, XV-02 approved these changes
Seems act as expected, with no obvious regression issues on desktop or laptop platforms, Looks largely good to go.

2022-03-16 15:10 UTC, jackpot51 approved these changes
This looks good to me now

2022-03-16 15:10 UTC, jackpot51 commented
@ids1024 it looks like there are conflicts that will need to be resolved.

2022-03-17 18:47 UTC, jackpot51 approved these changes

2022-03-17 19:26 UTC, Absolucy approved these changes

2022-04-27 00:03 UTC, XV-02 approved these changes
[Surreptitiously copy/pastes old review after testing everything again...]
Seems to act as expected, with no obvious regression issues on desktop or laptop platforms, Looks good to go.

2022-04-27 00:13 UTC, merged