Add check for thelio to get_default_graphics
pop-os/system76-power pull request #372
Opened 2022-11-28 22:35 UTC by jacobktm

Checks to see if the system is a thelio in get_default_graphics and enables hybrid graphics if true. This fixes [issue #370 ](https://github.com/pop-os/system76-power/issues/370)

2022-11-28 22:45 UTC, 13r0ck submitted a review, later dismissed

2022-11-28 22:48 UTC, crawfxrd requested changes
Desktops should be defaulting to discrete graphics.

Does NVIDIA support hybrid graphics in a desktop configuration? The Design Guides heavily imply it is for laptops only, but I can't find anything explicitly saying it's not supported like they do for RTD3.

2022-11-28 22:51 UTC, jacobktm commented
Yes, it does, as the function is currently it's been setting all of the desktops up with hybrid graphics. I can put that test on the discrete branch and I'm pretty sure that will work too.

2022-11-28 22:59 UTC, crawfxrd commented
Then it is wrong. Desktops should be set up with discrete graphics. They should also be returning `not switchable` when queried.

2022-11-28 23:02 UTC, jacobgkau commented
> Desktops should be set up with discrete graphics. They should also be returning `not switchable` when queried.

E.g. compute mode is a valid configuration for a Thelio (to output display from integrated graphics while using a dedicated GPU for compute.)

2022-11-28 23:22 UTC, crawfxrd commented on src/graphics.rs
> +        let thelio = product.contains("thelio");
This can be generalized by checking for any desktop: `cat /sys/class/dmi/id/chassis_type` = 0x03

2022-11-30 00:07 UTC, jacobktm commented
https://github.com/pop-os/system76-power/pull/373 is a much better fix for issue #370

2022-11-30 00:07 UTC, closed without merging